webexception/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
webexception/webexception.py,sha256=V-Y9IRU2iPp9MmUFKlxqNyihM2oUSx7MYb85_rz_bV0,643
webexception-1.0.4.dist-info/METADATA,sha256=lSHgrSodmnN6M5Kgqwrlvgn55GKXUoGh9LVswdB9FhU,6478
webexception-1.0.4.dist-info/WHEEL,sha256=7Z8_27uaHI_UZAc4Uox4PpBhQ9Y5_modZXWMxtUi4NU,88
webexception-1.0.4.dist-info/RECORD,,
